# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20160423_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeOptions',
            new_name='SizeOption',
        ),
    ]
