# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_auto_20160423_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzaingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_size', to='pizza.SizeOption'),
        ),
    ]
