# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20160501_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzasize',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='pizzasize',
            name='order_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
