# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0009_auto_20160501_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizzasize',
            options={'ordering': ['order_number']},
        ),
        migrations.RenameField(
            model_name='pizzasize',
            old_name='order_num',
            new_name='order_number',
        ),
    ]
